teleop_twist_joy_node:
  ros__parameters:
    enable_button: 4  # LB
    axis_linear:
      x: 1  # Left stick vertical
    scale_linear:
      x: 0.5
    axis_angular:
      yaw: 2  # Right stick horizontal
    scale_angular:
      yaw: 1.5
